# Generated by Django 3.1.7 on 2021-04-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210408_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='filedefault.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Threads',
        ),
    ]
