# Generated by Django 3.1.7 on 2021-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210408_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shortDescription',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
