# Generated by Django 3.1.7 on 2021-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='filedefault.jpg', null=True, upload_to='post_pictures'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shortDescription',
            field=models.TextField(blank=True),
        ),
    ]
